//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 03:11:15 PM CET 
//


package org.opentaps.module.ws.rest.domain.product;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opentaps.module.ws.rest.domain.product package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Product_QNAME = new QName("http://www.opentaps.org/module/ws/rest/domain/product", "product");
    private final static QName _Products_QNAME = new QName("http://www.opentaps.org/module/ws/rest/domain/product", "Products");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opentaps.module.ws.rest.domain.product
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductBean }
     * 
     */
    public ProductBean createProductBean() {
        return new ProductBean();
    }

    /**
     * Create an instance of {@link ProductsBean }
     * 
     */
    public ProductsBean createProductsBean() {
        return new ProductsBean();
    }

    /**
     * Create an instance of {@link ProductCategoryBean }
     * 
     */
    public ProductCategoryBean createProductCategoryBean() {
        return new ProductCategoryBean();
    }

    /**
     * Create an instance of {@link GoodIdentificationBean }
     * 
     */
    public GoodIdentificationBean createGoodIdentificationBean() {
        return new GoodIdentificationBean();
    }

    /**
     * Create an instance of {@link ProductPriceBean }
     * 
     */
    public ProductPriceBean createProductPriceBean() {
        return new ProductPriceBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentaps.org/module/ws/rest/domain/product", name = "product")
    public JAXBElement<ProductBean> createProduct(ProductBean value) {
        return new JAXBElement<ProductBean>(_Product_QNAME, ProductBean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductsBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentaps.org/module/ws/rest/domain/product", name = "Products")
    public JAXBElement<ProductsBean> createProducts(ProductsBean value) {
        return new JAXBElement<ProductsBean>(_Products_QNAME, ProductsBean.class, null, value);
    }

}
