//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.07 at 05:08:06 PM CEST 
//


package org.opentaps.module.ws.rest.domain.billing;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opentaps.module.ws.rest.domain.billing package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opentaps.module.ws.rest.domain.billing
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoicesBean }
     * 
     */
    public InvoicesBean createInvoicesBean() {
        return new InvoicesBean();
    }

    /**
     * Create an instance of {@link InvoiceItemBean }
     * 
     */
    public InvoiceItemBean createInvoiceItemBean() {
        return new InvoiceItemBean();
    }

    /**
     * Create an instance of {@link InvoiceBean }
     * 
     */
    public InvoiceBean createInvoiceBean() {
        return new InvoiceBean();
    }

}
