//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.07 at 08:22:48 PM CEST 
//


package org.opentaps.module.ws.rest.domain.billing;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opentaps.module.ws.rest.domain.billing package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Invoice_QNAME = new QName("http://www.opentaps.org/module/ws/rest/domain/billing", "invoice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opentaps.module.ws.rest.domain.billing
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoicesBean }
     * 
     */
    public InvoicesBean createInvoicesBean() {
        return new InvoicesBean();
    }

    /**
     * Create an instance of {@link InvoiceBean }
     * 
     */
    public InvoiceBean createInvoiceBean() {
        return new InvoiceBean();
    }

    /**
     * Create an instance of {@link InvoiceItemBean }
     * 
     */
    public InvoiceItemBean createInvoiceItemBean() {
        return new InvoiceItemBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentaps.org/module/ws/rest/domain/billing", name = "invoice")
    public JAXBElement<InvoiceBean> createInvoice(InvoiceBean value) {
        return new JAXBElement<InvoiceBean>(_Invoice_QNAME, InvoiceBean.class, null, value);
    }

}
