//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.07 at 08:22:48 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opentaps.org/module/ws/rest/domain/billing", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opentaps.module.ws.rest.domain.billing;
